name: DBM-Offline test diff
run-name: DBM-Offline on PR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dbm-offline-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Run DBM-Offline
        uses: DeadlyBossMods/DBM-Offline@main
        with:
          repo-under-test: vanilla
          dbm-mod-ref-vanilla: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}
          dbm-mod-base-ref-vanilla: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          test-dbm-vanilla-mods: true
