name: DBM-Offline test diff
run-name: DBM-Offline

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  dbm-offline-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Run DBM-Offline
        continue-on-error: true
        uses: DeadlyBossMods/DBM-Offline@main
        with:
          dbm-mod-repo: DeadlyBossMods/DBM-Vanilla
          dbm-mod-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}
          dbm-mod-base-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          upload-repo: emmericp/test-github-actions
          upload-token: ${{ secrets.DBM_OFFLINE_UPLOAD_TOKEN }}
